#+TITLE: 職務履歴書
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil

* 基本情報

|----------+----------------------------|
| key      | value                      |
|----------+----------------------------|
| Name     | 原田  経道(はらだつねみち) |
| Twitter  | [[https://twitter.com/tsu_nera][tsu-nera(@tsu_nera)]]        |
| Facebook | [[https://www.facebook.com/tsunemichi.harada][原田 経道]]                  |
| Github   | [[https://github.com/tsu-nera][tsu-nera]]                   |
| LinkedIn | [[https://www.linkedin.com/profile/preview?locale=en_US&trk=prof-0-sb-preview-primary-button][Tsunemichi Harada]]          |
| Quita    | [[http://qiita.com/tsu_nera][tsu_nera]]                   |
| Blog     | http://futurismo.biz       |
| Kaggle   | [[https://www.kaggle.com/fox10225fox][tsu-nera]]                   |
| TopCoder | [[https://www.topcoder.com/members/tsu_nera][tsu_nera]]                   |
|----------+----------------------------|

|----------+------------------------|
| 性別     | 男                     |
| 生年月日 | 1986/10/25             |
| 現住所   | 神奈川県 川崎市 中原区 |
| mail     | fox10225fox@gmail.com  |
|----------+------------------------|

* 言語
|----------+--------------|
| 自然言語 | 備考         |
|----------+--------------|
| 日本語   | ネイティブ   |
| English  | 日常会話程度 |
|----------+--------------|

* 学歴

| 　学校名                    |      所属年月 |
|-----------------------------+---------------|
| 巣鴨高校                    | 200204-200503 |
| 東京理科大学 数理情報科学科 | 200604-201003 |
(柳田研究室　専攻: 情報理論)

* プログラミング言語
  - 実務経験あり: C 言語, Ruby, Java
  - 趣味: C++, Scala, Clojure, Python, 他

* 職務経歴
  2010/04 - （現在）: 株式会社富士通コンピュータテクノロジーズ
  ソフトウェア開発者 (Fujitsu Computer Technologies Liminted)
  - ETERNUS DX フォームウェア開発 201004-201401
  - 統合保守エンジン開発 201402-201407
  - WAN 高速化開発 201408-201502 
    [[http://pr.fujitsu.com/jp/news/2015/06/22.html][遠隔地からのファイルアクセスを高速化するデータ転送技術を開発 : 富士通]]
  - AGL プロジェクト 研究開発 201503-201506
  - ServerView Infrastructure Manager 201507-201512
  - 休職 201512-(現在)

* 資格
  - 応用情報技術者試験
  - UMTP L1/L2
  - LPIC L1
  - TOEIC L&R Score 860

* 特許
  - [[http://patent.newsln.jp/p/2016151850][特開 2016-151850 - PatentNewsln]]
* 心がけていること
** 成功の定義
  - プログラミングを通じてお金を稼ぎ、 テクノロジーの発展に貢献すること。
  - 常に努力を怠らず、 目標を持って仕事に情熱を燃やすこと。
  - 英語を駆使して世界で活躍する、 ソフトウェア開発者になること。
   
** 目標
*** 短期目標
  - TOEIC860 スコアを取ること。 (達成: 2017/03)

*** 中期目標
  - 英会話と英作文の勉強をすること。
  - 機械学習の勉強をすること
  - TOEIC900 スコアを取ること。 

*** 長期目標
  - 機械学習の知識を利用できる仕事をすること。 
  - 英語ができるプログラマになること。 
  - カンファレンスで英語でプレゼンして質疑応答ができること。 
  - 海外の技術情報を素早く手に入れ理解すること。

** 信念
  - 小さいことを積み重ねることが、 とんでもないところへ行くただひとつの道
  - スピードよりも着実な理解を優先する
  - やる気がでないときは勉強する意味を考える
  - 達成よりも学習の過程を重視する
  - 屈辱をモチベーションに変える
  - この世で目標を達成するために与えられた時間には限りがある
  - 他人と自分を比較しない、自分は必ず目標を達成できる。 自分を信じること
  - GRIT(やり抜く力） 才能は努力で克服できる
  - 成長思考−努力は必ず報われると信じる
  - 興味をもつ、練習を続ける、目的をもつ、希望を持つ

* MOOC 受講履歴
1) Algorithms, Part I - coursera 2013/11
2) Algorithms, Part II - coursera 2014/02
3) C++ For C Programmers - coursera 2014/02
4) Creative, Serious and Playful Science of Android Apps - coursera 2014/02
5) Programming Mobile Applications for Android Handheld Systems - courserea 2014/03
6) Unlocking the Immunity to Change: A New Approach to Personal Improvement - edX 2014/03
7) Web Application Architectures - coursera 2013/06
8) Pattern-Oriented Software Architectures: Programming Mobile Services for Android Handheld Systems - coursera 2014/07
9) The Hardware/Software Interface - coursera 2014/09
10) Programming Cloud Services for Android Handheld Systems - coursera 2014/09
11) Introduction to Linux - edX 2014/12
12) Paradigms of Computer Programming -Fundamentals - coursera 2014/12
13) Computational Investing, Part I - coursera 2014/12
14) Survey of Music Technology - coursera 2014/12
15) Introduction to Functional Programming - edX 2014/12
16) Louv1.2x: Paradigms of Computer Programming - Abstraction and Concurrency - edX 2015/02
17) The Data Scientist ’ s Toolbox - coursera 2015/02
18) R Programming - coursera 2015/02
19) Reproducible Research coursera 2015/03
20) Cloud Computing Concepts PartI - coursera 2015/03
21) Cloud Computing Concepts PartII - coursera 2015/04
22) edX Honor Code Certificate for Foundations of Data Analysis - edX 2015/03
23) Principles of Reactive Programming - coursera 2015/05
24) From Nand to Tetris / Part I - coursera 2015/05
25) Success - coursera 2016/12
26) Programming Languages PartA - coursera 2016/12 [[https://www.coursera.org/account/accomplishments/certificate/KB24LCCEPQL6][certificate]]
27) Programming Languages PartB - coursera 2017/01 [[https://www.coursera.org/account/accomplishments/certificate/ZQJJNSZT74H2][certificate]]
28) Programming Languages PartC - coursera 2017/01 [[https://www.coursera.org/account/accomplishments/certificate/CTXKUYXKDVC7][certificate]]
29) Machine Learning - coursera 2017/02 [[https://www.coursera.org/account/accomplishments/certificate/YUBG2A7K87ND][certificate]]
30) Creative Applications of Deep Learning with TensorFlow - kadenze [[https://www.kadenze.com/certificates/verified/AW1D6GZP][certificate]]
